### ISSUE TITLE
site remains same or will be new this year?

### ISSUE THREAD

**Issue by stalwart201** [GniotTechClub/Official-site#4]
@rajatvaidya14 as if there will be a new site than we should better start working on it rather making changes in this one.

**Comment by rajataaron** [comment]
No, site remains same we can add features to it.

**Comment by stalwart201** [comment]
so if it remains same. we should assign the work by creating further issue and assign everyone to work on them accordingly.

**Comment by rajataaron** [comment]
ok, that will great.

**Comment by juggernaut451** [comment]
issue resolved 
hence closing issue!!
